export const ADMIN_GETUSERS_INIT = "ADMIN_GETUSERS_INIT";
export const ADMIN_GETUSERS_SUCCESS = "ADMIN_GETUSERS_SUCCESS";
export const ADMIN_GETUSERS_FAILED = "ADMIN_GETUSERS_FAILED";
export const ADMIN_GETUSERS_RESET = "ADMIN_GETUSERS_RESET";
